name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}:${{ github.ref }}:linux
      cancel-in-progress: true
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@cb986078a5bd4775e5fb05348f3618e41fedf4de # v4.0.0
    with:
      fmt: true
      lint: true
      test: true
      build: true

  macos:
    name: macOS
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}:${{ github.ref }}:macos
      cancel-in-progress: true
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@cb986078a5bd4775e5fb05348f3618e41fedf4de # v4.0.0
    with:
      runner: macos-latest
      test: true
