name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}:${{ github.ref }}:linux
      cancel-in-progress: true
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@0a310f1286537ed4fd000af4b35cd6459b00448d
    with:
      fmt: true
      lint: true
      test: true
      build: true

  macos:
    name: macOS
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}:${{ github.ref }}:macos
      cancel-in-progress: true
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@0a310f1286537ed4fd000af4b35cd6459b00448d
    with:
      runner: macos-latest
      test: true
